name: Release

on:
  push:
    branches:
        - 'main'
        - 'pre-release'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch
          persist-credentials: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to GitHub Packages
        env:
          # PAT needs to be created in Repo with Brach protection rule allowed for required branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
